In [48]:
import glob
import random
import os
import numpy as np
import torch
from torch.utils.data import Dataset
from PIL import Image
import torchvision.transforms as transforms
import os
import os.path as osp

In [84]:
path = '/media/arg_ws3/5E703E3A703E18EB/data/subt_real_ssd/JPEGImages/scene000001_4.png'
img = Image.open(path)
img = np.array(img)
img

array([[3829, 3829, 3829, ..., 2236, 2236, 2228],
       [3829, 3829, 3853, ..., 2236, 2236, 2228],
       [3829, 3829, 3853, ..., 2236, 2236, 2228],
       ...,
       [   0,    0,    0, ...,  279,  279,  279],
       [   0,    0,    0, ...,  279,  279,  279],
       [   0,    0,    0, ...,  279,  279,  279]], dtype=int32)

In [85]:
img = img/10000.
img

array([[0.3829, 0.3829, 0.3829, ..., 0.2236, 0.2236, 0.2228],
       [0.3829, 0.3829, 0.3853, ..., 0.2236, 0.2236, 0.2228],
       [0.3829, 0.3829, 0.3853, ..., 0.2236, 0.2236, 0.2228],
       ...,
       [0.    , 0.    , 0.    , ..., 0.0279, 0.0279, 0.0279],
       [0.    , 0.    , 0.    , ..., 0.0279, 0.0279, 0.0279],
       [0.    , 0.    , 0.    , ..., 0.0279, 0.0279, 0.0279]])

In [86]:
inv_normalize = transforms.Compose([ 
                transforms.Normalize(mean = [ 0., 0., 0. ],
                                             std = [ 1/0.5, 1/0.5, 1/0.5 ]),
                transforms.Normalize(mean = [ -0.5, -0.5, -0.5 ],
                                             std = [ 1., 1., 1. ]),
                ])

In [87]:
pil_img = Image.fromarray(img)
transforms_ = [ transforms.Resize((256, 256), Image.BICUBIC),
                transforms.ToTensor(),
                transforms.Normalize((0.5,0.5,0.5), (0.5,0.5,0.5)) ]
transform_img = transforms.Compose(transforms_)
pil_img = transform_img(pil_img)

In [88]:
pil_img = pil_img.cpu().detach()
pil_img = inv_normalize(pil_img)
pil_img

tensor([[[0.3828, 0.3849, 0.3895,  ..., 0.2261, 0.2242, 0.2233],
         [0.3850, 0.3878, 0.3916,  ..., 0.2261, 0.2242, 0.2233],
         [0.3920, 0.3924, 0.3951,  ..., 0.2261, 0.2243, 0.2231],
         ...,
         [0.0000, 0.0000, 0.0000,  ..., 0.0180, 0.0142, 0.0193],
         [0.0000, 0.0000, 0.0000,  ..., 0.0299, 0.0286, 0.0290],
         [0.0000, 0.0000, 0.0000,  ..., 0.0280, 0.0279, 0.0279]]])

In [66]:
pil_img = pil_img.mul(10000).clamp(0, 10000).to(torch.int16).permute(1, 2, 0)

In [67]:
cv_img = (np.array(pil_img)*10000).astype(np.uint16)
cv_img.shape

(256, 256, 1)